#
# Executes commands at login pre-zshrc.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim -Xo'
export VISUAL='gvim -Xo'
export PAGER='less -e'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

export EXINIT="set ts=2 redraw sh=$SHELL dir=/tmp showmode smartindent nows ruler nowrapscan nu"

export WORDCHARS="*?_-.[]~=&!#$%^(){}<>"
export ZLE_RPROMPT_INDENT=1

export    ecd=ec.coraid.com
export     dt=$HOME/Desktop
export     db=$HOME/Dropbox
export     dl=$HOME/Downloads
export   nook=/media/NOOK

export EC_USERNAME=admin
export EC_PASSWORD=ChangeMe\!
export EC_LOGIN=test
export EC_CERTS=TRUST_ALL

export EC_YAML_DIR=$HOME/yaml

export GIT_SSH=$HOME/bin/ssh4git
export sasi=$HOME/sasi
export      core=$sasi/src/main/scala/core
export  restypes=$sasi/src/main/scala/restypes
export resources=$sasi/src/main/resources

HISTSIZE=10000
SAVEHIST=10000
# export DIRSTACKSIZE=9

# DEBIAN_PREVENT_KEYBOARD_CHANGES=yes
# https://github.com/robbyrussell/oh-my-zsh/issues/1433

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /{,usr/}{,s}bin
  /usr/local/bin
  /usr/bin/X11
  ~/bin
	~/scala/bin
	~/coraiddevtools/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

setopt \
  auto_param_keys \
  auto_param_slash \
  auto_remove_slash \
  complete_aliases \
  list_packed \
  case_glob \
  case_match \
  magic_equal_subst \
  numeric_glob_sort \
  rc_expand_param \
  extended_history \
  hist_allow_clobber

unsetopt \
  share_history
